stages:
  - build
  - test
  - package
  - cleanup
  - deploy
    
make_rpm:
  stage: test
  tags:
    - custom
  script:
    - make rpm > make_agent_rpm_out
    - rpm_path=`cat make_agent_rpm_out | grep rpmbuild/RPMS/ | cut -d' ' -f2`
    - echo $rpm_path 
    - sudo rm /var/lib/rpm/.rpm.lock || echo
    - sudo yum remove -y cerndb-infra-db-flume-agent
    - sudo rpm -i $rpm_path
    - /usr/lib/db-flume-agent/bin/version
    - \[ -f /usr/lib/db-flume-agent/bin/db-flume-agent \]
    - \[ -f /etc/init.d/db-flume-agent \]
    - \[ -d /var/log/db-flume-agent/ \]
    - \[ -d /var/lib/db-flume-agent/ \]
    - \[ -d /var/run/db-flume-agent/ \]
    - \[ -d /etc/flume-ng/db-flume-agent/ \]
    - sleep 10
    - sudo service db-flume-agent status

cleanup_rpm_deployment:
  # it will do the clean up only on one of the runners
  stage: cleanup
  tags:
    - custom
  script:
    - sudo service db-flume-agent stop || echo Failed
    - sudo yum remove -y cerndb-infra-db-flume-agent || echo Failed
    - sudo rm -rf /etc/flume-ng/db-flume-agent/ || echo Failed
    - sudo rm -rf /var/log/db-flume-agent/ || echo Failed
    - sudo service db-flume-agents-gateway stop || echo Failed
    - sudo yum remove -y cerndb-infra-db-flume-agents-gateway || echo Failed
    - sudo rm -rf /etc/flume-ng/db-flume-agents-gateway/ || echo Failed
    - sudo rm -rf /var/log/db-flume-agents-gateway/ || echo Failed
  when: always  
          
deploy_rpm:
  # Run only if spec file was modified
  stage: deploy
  tags:
    - custom
  script:
    - spec_modif=`git diff-tree --no-commit-id --name-only -r HEAD | grep .spec` || echo Spec file was not modified, so deployment will not take place
    - \[ -z "$spec_modif" \] || kinit -k -t ~/dblogs.keytab dblogs@CERN.CH
    - \[ -z "$spec_modif" \] || make build > make_build_out
    - \[ -z "$spec_modif" \] || cat make_build_out
    - \[ -z "$spec_modif" \] || task_id=`cat make_build_out | grep "Created task:" | head -1 | cut -d" " -f3`
    - \[ -z "$spec_modif" \] || koji watch-task $task_id
    - \[ -z "$spec_modif" \] || task_id=`cat make_build_out | grep "Created task:" | tail -1 | cut -d" " -f3`
    - \[ -z "$spec_modif" \] || koji watch-task $task_id
    - \[ -z "$spec_modif" \] || make tag-qa
    
    