stages:
  - build
  - test
  - package

variables:
  JDBC_DRIVER: 'lib/mariadb-java-client.jar'
    
before_script:
  - cat src/test/resources/prepare-test.sql | /usr/bin/mysql -u root --password=
    
compile:
  stage: build
  script:   
    - bin/compile
  artifacts:
    expire_in: 5 mins
    paths:
      - target/
    
avro_schema_utility:
  stage: test
  script:
    - mkdir -p lib
    - wget -O $JDBC_DRIVER http://central.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/1.1.9/mariadb-java-client-1.1.9.jar
    - bin/infer-avro-schema-from-table -dc org.mariadb.jdbc.Driver -c jdbc:mariadb://localhost/testdb -t customers -u testuser -p password > out
    - cat out
    - \[ `cat out | grep -v INFO | wc -l` -eq 17 \] 
  dependencies:
    - compile
    
jdbc_source:
  stage: test
  script:  
    - mkdir -p lib
    - wget -O $JDBC_DRIVER http://central.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/1.1.9/mariadb-java-client-1.1.9.jar
    - timeout 10s /usr/lib/aimon-flume-ng/bin/flume-ng agent --classpath $JDBC_DRIVER:target/* -n test_agent -f src/test/ci/source-agent/agent.conf -c src/test/ci/source-agent/ > out &
    - sleep 10
    - cat out
    - \[ `cat out | grep LoggerSink | wc -l` -eq 3 \]
  dependencies:
    - compile
    
make_rpm:
  stage: test
  script:
    - make rpm > make_rpm_out
    - rpm_path=`cat make_rpm_out | grep rpmbuild/RPMS/ | cut -d' ' -f2`
    - echo $rpm_path 
    
    
    
          