stages:
  - build
  - deploy

build:
  stage: build
  image: docker.cern.ch/cloud-infrastructure/gitbook-ebook
  except:
        - master
  script:
    - rm -rf $CI_PROJECT_DIR/_book
    - gitbook build $CI_PROJECT_DIR $CI_PROJECT_DIR/_book
    - gitbook pdf $CI_PROJECT_DIR $CI_PROJECT_DIR/book.pdf
  artifacts:
    paths:
      - _book
      - book.pdf
  tags:
      - docker

deploy:
  stage: deploy
  image: fellah/gitbook-ebook
  only:
    - gitbook
  script:
    - rm -rf $CI_PROJECT_DIR/_book
    - gitbook build $CI_PROJECT_DIR $CI_PROJECT_DIR/_book
    - gitbook pdf $CI_PROJECT_DIR $CI_PROJECT_DIR/book.pdf
    - apt-get install sshpass
    - SSHPASS=$DBWEBDOC_PASSWORD sshpass -e scp -oStrictHostKeyChecking=no -r $CI_PROJECT_DIR/_book/* dbwebdoc@lxplus.cern.ch:$AFS_DOCS_LOCATION
  tags:
    - docker