stages:
  - deploy

build_and_deploy:
  stage: deploy
  image: fellah/gitbook-ebook
  only:
    - gitbook
  script:
    - rm -rf $CI_PROJECT_DIR/_book
    - gitbook build $CI_PROJECT_DIR $CI_PROJECT_DIR/_book
    - gitbook pdf $CI_PROJECT_DIR $CI_PROJECT_DIR/book.pdf
    - apt-get update
    - apt-get install -y sshpass
    - SSHPASS=$DBWEBDOC_PASSWORD sshpass -e scp -oStrictHostKeyChecking=no -r $CI_PROJECT_DIR/_book/* dbwebdoc@lxplus.cern.ch:$AFS_DOCS_LOCATION
  tags:
    - docker