stages:
  - build
  - test
  - package
  - cleanup
  - deploy

make_rpm:
  stage: test
  tags:
    - custom
  script:
    - make rpm > make_rpm_out
    - rpm_path=`cat make_rpm_out | grep rpmbuild/RPMS/ | cut -d' ' -f2`
    - echo $rpm_path 
    - sudo rm /var/lib/rpm/.rpm.lock || echo
    - sudo yum remove -y cerndb-infra-db-flume-agents-gateway
    - sudo rpm -i $rpm_path
    - /usr/lib/db-flume-agents-gateway/bin/version
    - \[ -f /usr/lib/db-flume-agents-gateway/bin/db-flume-agents-gateway \]
    - \[ -f /etc/init.d/db-flume-agents-gateway \]
    - \[ -d /var/log/db-flume-agents-gateway/ \]
    - \[ -d /var/lib/db-flume-agents-gateway/ \]
    - \[ -d /var/run/db-flume-agents-gateway/ \]
    - \[ -d /etc/flume-ng/db-flume-agents-gateway/ \]
    - sleep 10
    - sudo service db-flume-agents-gateway status
    
cleanup_rpm_deployment:
  # it will do the clean up only on one of the runners
  stage: cleanup
  tags:
    - custom
  script:
    - sudo service db-flume-agents-gateway stop || echo Failed
    - sudo yum remove -y cerndb-infra-db-flume-agents-gateway || echo Failed
    - sudo rm -rf /etc/flume-ng/db-flume-agents-gateway/ || echo Failed
    - sudo rm -rf /var/log/db-flume-agents-gateway/ || echo Failed
  when: always  
          
deploy_rpm:
  stage: deploy
  tags:
    - custom
  script:
    - kinit -k -t ~/dblogs.keytab dblogs@CERN.CH
    - make build > make_build_out
    - cat make_build_out
    - task_id=`cat make_build_out | grep "Created task:" | head -1 | cut -d" " -f3`
    - koji watch-task $task_id
    - task_id=`cat make_build_out | grep "Created task:" | tail -1 | cut -d" " -f3`
    - koji watch-task $task_id
    - make tag-qa
    
    